[http]
  ################################################################
  # Middleware
  ################################################################
  [http.middlewares]
    # create middleware to enable basic authentication (htpasswd -nB adm)
    [http.middlewares.authbasic.basicAuth]
      users=[
       "admin:$2y$05$m/DNEUenlOKATbB8EXjbbOZN1uDzuqnS/Fj0NRh5GMiJS8lPUjIEG"
      ]
    # create middleware to enable tls redirect scheme
    [http.middlewares.tls_middleware.redirectScheme]
      scheme = "https"
      permanent = true

[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/srv/certs/server-cert.pem"
        keyFile  = "/srv/certs/server-key.pem"
  [[tls.certificates]]
    certFile = "/srv/certs/server-cert.pem"
    keyFile = "/srv/certs/server-key.pem"
    stores = ["default"]
